import type {Metadata} from "next";
import {Inter, Poppins} from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/app/Components/Navbar";

const inter = Inter({subsets: ["latin"]});

const poppins = Poppins({
    subsets: ["latin"],
    variable: '--font-poppins',
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Quiz Maker</title>
        </head>
        <body className={poppins.variable}>
        <header>
            <Navbar></Navbar>
        </header>
            <main>
                {children}
            </main>
        </body>
        </html>
    );
}
